
CREATE TABLE `workflow_category` ( `ID` int(11) NOT NULL, `NAME` varchar(255) NOT NULL, `DESCRIPTION` varchar(255) DEFAULT NULL, `LOGO` varchar(255) DEFAULT NULL,
  `CREATE_AT` datetime NOT NULL, `UPDATE_AT` datetime DEFAULT NULL, `ENABLED` int(11) NOT NULL, `PARENT_ID` int(11) DEFAULT NULL, PRIMARY KEY (`ID`));
ALTER TABLE `workflow_category` ADD CONSTRAINT `fk_workflow_category_parent` FOREIGN KEY (`PARENT_ID`) REFERENCES `workflow_category`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE `workflow` (`ID` int(11) NOT NULL, `NAME` varchar(255) NOT NULL, `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ENABLED` int(11) NOT NULL, `WORKFLOW_CATEGORY_ID` int(11) NOT NULL, PRIMARY KEY (`ID`));
ALTER TABLE `workflow` ADD CONSTRAINT `fk_workflow_workflow_category` FOREIGN KEY (`WORKFLOW_CATEGORY_ID`) REFERENCES `workflow_category`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE `workflow_variant` (`WORKFLOW_ID` int(11) NOT NULL,`VARIANT_ID` int(11) NOT NULL);
ALTER TABLE `workflow_variant` ADD CONSTRAINT `fk_workflow_variant` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `workflow`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `workflow_variant` ADD CONSTRAINT `fk_variant_workflow` FOREIGN KEY (`VARIANT_ID`) REFERENCES `workflow`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
